### ISSUE TITLE
Creating images from online url

### ISSUE THREAD

**Issue by Youngestdev** [Youngestdev/favico-generator#4]
Currently, the favicon generator only works with images locally, what about using it to generate favicons from an image passed through a llink ? I mean : 

```sh
favico-generator --file https://example.com/hello.png
```

I think this would be pretty nice.

**Comment by max-arias** [comment]
Hey @Youngestdev, mind if I grab this one?

**Comment by Youngestdev** [comment]
Not at all, feel free.

**Comment by Youngestdev** [comment]
#5 :tada:
